# Site settings
title: Graph Commons Hackathons
header-img: img/home-cover.jpg
email: contact@graphcommons.com
description: Together we untangle those relations
baseurl: "/hackathons"
url: "http://graphcommons.github.io"
twitter_username: graphcommons
github_username:  graphcommons
facebook_username:  graphcommons

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
