# Site settings
title: Graph Commons Hackathons
header-img: img/home-cover-2.jpg
email: workshop@graphcommons.com
description: Graph Commons is a collaborative platform for mapping, analyzing and publishing data-networks.
baseurl: "/hackathons"
url: "http://graphcommons.github.io"
twitter_username: graphcommons
facebook_username:  graphcommons
github_username:  graphcommons
slack_team:  graphcommons

# Build settings
markdown: kramdown
# highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
future: true
plugins:
    - jekyll-paginate
